# Generated by Django 6.0.1 on 2026-01-29 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='times_of_issued',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
