# Generated by Django 6.0.1 on 2026-02-01 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lib_app', '0004_book_pages_alter_book_isbn_alter_book_key_words_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='pages',
        ),
    ]
