# Generated by Django 6.0.1 on 2026-02-01 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lib_app', '0006_alter_book_author_alter_book_publisher_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='year_of_publication',
            new_name='year',
        ),
    ]
