# Generated by Django 6.0.1 on 2026-02-05 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_app', '0008_user_cart_borrowedbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
