# Generated by Django 6.0.1 on 2026-02-09 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_app', '0009_alter_book_isbn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='thematic',
        ),
        migrations.AddField(
            model_name='book',
            name='short_description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='key_words',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
